# Docker Compose for Socket.IO Signaling Server
version: '3.8'

services:
  signaling-server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CLIENT_ORIGIN=http://localhost:5173
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - signaling-network

  # Redis for scaling (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - signaling-network
    profiles:
      - scaling

  # Nginx load balancer (for multiple signaling servers)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - signaling-server
    restart: unless-stopped
    networks:
      - signaling-network
    profiles:
      - production

volumes:
  redis_data:

networks:
  signaling-network:
    driver: bridge